home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import contactView, successView

app_name = 'home'
urlpatterns = [
    path('', views.index, name='home'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('contact/', contactView, name='contact'),
    path('success/', successView, name='success'),
    path('send-newsletter/', views.send_newsletter, name='send_newsletter'),
    path('unsubscribe/<str:email>/', views.unsubscribe, name='unsubscribe'),
    path('secret-lab/', views.easter_egg, name='easter_egg'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labmunkznetwork/urls.py
"""labmunkznetwork URL Configuration
"""
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.conf.urls import url

admin.site.site_header = "Labmunkz Network"
admin.site.index_title = "Database administration configuration."

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    #path('api/', include('api.urls')),
    path('group/', include('group.urls')),
    path('munkz/', include('munkz.urls')),
    path("music/", include("music.urls")),
    path("polls/", include("polls.urls")),
    path('shop/', include('shop.urls')),
   # path('asset/', include('asset.urls')),
    path('client/', include('client.urls')),
   # url(r'^filer/', include('filer.urls')),
   # path('helpdesk/', include('helpdesk.urls')),
    path('jobsite/', include('jobsite.urls')),
    path('project/', include('project.urls')),
    path('material/', include('material.urls')),
    path('posts/', include('posts.urls')),
    path('schedule/', include('schedule.urls', namespace='schedule')),
    path('timecard/', include('timecard.urls')),
    path('todo/', include('todo.urls', namespace="todo")),
   # path('wip/', include('wip.urls')),
]
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views

urlpatterns = [
    path(    '',                                  views.ProjectMain,               name='project'),
    path(    'list/',                             views.ProjectListView.as_view(), name='project-list'),
    url(    r'create-project/(?P<jobsi>[0-9]+)$', views.ProjectCreateView,         name='create-project-from'),
    url(    r'update-project/(?P<pk>[0-9]+)/$',   views.ProjectUpdate.as_view(),   name='update-project'),
    url(    r'main/(?P<pk>[0-9]+)/delete/$',      views.ProjectDelete.as_view(),   name='delete-project'),
    re_path(r'^detail/(?P<job_num>\d+)$',         views.ProjectDeView,             name='project-detail'),

    #re_path(r'^project-quote/(?P<job_num>\d+)$',  views.project_quote_view,        name='project-quote'),  
    re_path(r'^render/pdf/(?P<job_num>\d+)$',     views.project_detail_pdf,        name='project-pdf'),
    
    path(    'project-scope/',                 views.ScopeMain,                   name='scope-of-work'),
    url(    r'create-scope/(?P<proj>[0-9]+)$', views.ScopeOfWorkCreateView,       name='create-scope-of-work'),
    re_path(r'^scope/detail/(?P<id>\d+)$',     views.ScopeOfWorkDeView,           name='scope-detail'),
    url(    r'update-scope/(?P<pk>[0-9]+)/$',  views.ScopeOfWorkUpdate.as_view(), name='update-scope-of-work'),
    url(    r'scope/(?P<pk>[0-9]+)/delete/$',  views.ScopeOfWorkDelete.as_view(), name='delete-scope-of-work'),

    path(    'project-device/',                            views.ProjectDevice,                 name='project-device'),
    url(    r'create-device/(?P<proj>\d+)/(?P<tas>\d+)/$', views.ProjectDeviceCreateView,       name='create-project-device'),
    re_path(r'^device-detail/(?P<id>\d+)$',                views.ProjectDeviceDeView,           name='project-device-detail'),
    url(    r'update-device/(?P<pk>[0-9]+)/$',             views.ProjectDeviceUpdate.as_view(), name='update-project-device'),
    url(    r'device/(?P<pk>[0-9]+)/delete/$',             views.ProjectDeviceDelete.as_view(), name='delete-project-device'),

    path(    'project-wire/',                            views.ProjectWire,                 name='project-wire'),
    url(    r'create-wire/(?P<proj>\d+)/(?P<tas>\d+)/$', views.ProjectWireCreateView,       name='create-project-wire'),
    re_path(r'^wire-detail/(?P<id>\d+)$',                views.ProjectWireDeView,           name='project-wire-detail'),
    url(    r'update-wire/(?P<pk>[0-9]+)/$',             views.ProjectWireUpdate.as_view(), name='update-project-wire'),
    url(    r'wire/(?P<pk>[0-9]+)/delete/$',             views.ProjectWireDelete.as_view(), name='delete-project-wire'),

    path(    'project-hardware/',                            views.ProjectHardware,                 name='project-hardware'),
    url(    r'create-hardware/(?P<proj>\d+)/(?P<tas>\d+)/$', views.ProjectHardwareCreateView,       name='create-project-hardware'),
    re_path(r'^hardware-detail/(?P<id>\d+)$',                views.ProjectHardwareDeView,           name='project-hardware-detail'),
    url(    r'update-hardware/(?P<pk>[0-9]+)/$',             views.ProjectHardwareUpdate.as_view(), name='update-project-hardware'),
    url(    r'hardware/(?P<pk>[0-9]+)/delete/$',             views.ProjectHardwareDelete.as_view(), name='delete-project-hardware'),

    path(    'project-software/',                            views.ProjectSoftware,                 name='project-software'),
    url(    r'create-software/(?P<proj>\d+)/(?P<tas>\d+)/$', views.ProjectSoftwareCreateView,       name='create-project-software'),
    re_path(r'^software-detail/(?P<id>\d+)$',                views.ProjectSoftwareDeView,           name='project-software-detail'),
    url(    r'update-software/(?P<pk>[0-9]+)/$',             views.ProjectSoftwareUpdate.as_view(), name='update-project-software'),
    url(    r'software/(?P<pk>[0-9]+)/delete/$',             views.ProjectSoftwareDelete.as_view(), name='delete-project-software'),

    path(    'project-license/',                            views.ProjectLicense,                 name='project-license'),
    url(    r'create-license/(?P<proj>\d+)/(?P<tas>\d+)/$', views.ProjectLicenseCreateView,       name='create-project-license'),
    re_path(r'^license-detail/(?P<id>\d+)$',                views.ProjectLicenseDeView,           name='project-license-detail'),
    url(    r'update-license/(?P<pk>[0-9]+)/$',             views.ProjectLicenseUpdate.as_view(), name='update-project-license'),
    url(    r'license/(?P<pk>[0-9]+)/delete/$',             views.ProjectLicenseDelete.as_view(), name='delete-project-license'),

    path(    'project-travel/',                            views.ProjectTravel,                 name='project-travel'),
    url(    r'create-travel/(?P<proj>\d+)/(?P<tas>\d+)/$', views.ProjectTravelCreateView,       name='create-project-travel'),
    re_path(r'^travel-detail/(?P<id>\d+)$',                views.ProjectTravelDeView,           name='project-travel-detail'),
    url(    r'update-travel/(?P<pk>[0-9]+)/$',             views.ProjectTravelUpdate.as_view(), name='update-project-travel'),
    url(    r'travel/(?P<pk>[0-9]+)/delete/$',             views.ProjectTravelDelete.as_view(), name='delete-project-travel'),
]

schedule/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from django.views.generic.list import ListView
from . import views
#CalendarICalendar, 
from schedule.feeds import UpcomingEventsFeed
from schedule.models import Calendar
from schedule.periods import Day, Month, Week, Year
from schedule.views import (
    CalendarByPeriodsView, CalendarView, CancelOccurrenceView, CreateEventView, EventCreateView,
    CreateOccurrenceView, DeleteEventView, EditEventView, EditOccurrenceView,
    EventView, FullCalendarView, OccurrencePreview, OccurrenceView,
    api_move_or_resize_by_code, api_occurrences, api_select_create, EventTodayArchiveView, EventDayArchiveView,
)
app_name = 'schedule'
urlpatterns = [
    #re_path(r'^detail/schedule/(?P<pk>\d+)$', views.DayEventDetailView.as_view(), name='event-detail'),
    #path('create-event/', views.EventCreate.as_view(), name='create-event'), 
    url(r'create-event/(?P<proj>[0-9]+)$', views.EventCreateView, name='create-event'), 
    #url(r'schedule/update-event/(?P<pk>[0-9]+)/$', views.DayEventUpdate.as_view(), name='update-event'),
    #url(r'schedule/event/(?P<pk>[0-9]+)/delete/$', views.DayEventDelete.as_view(), name='delete-event'),
    path('today/', EventTodayArchiveView.as_view(), name='archive_today'),
    path('<int:year>/<str:month>/<int:day>/', EventDayArchiveView.as_view(), name='archive_day'),

    url(r'^$', ListView.as_view(model=Calendar), name='calendar_list'),

    url(r'^calendar/year/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_year.html'),
        name='year_calendar',
        kwargs={'period': Year}),

    url(r'^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_tri_month.html'),
        name='tri_month_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_compact_month.html'),
        name='compact_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_month.html'),
        name='month_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/week/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_week.html'),
        name='week_calendar',
        kwargs={'period': Week}),

    url(r'^calendar/daily/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_day.html'),
        name='day_calendar',
        kwargs={'period': Day}),

    url(r'^calendar/(?P<calendar_slug>[-\w]+)/$',
        CalendarView.as_view(),
        name='calendar_home',
        ),
    url(r'^fullcalendar/(?P<calendar_slug>[-\w]+)/$',
        FullCalendarView.as_view(),
        name='fullcalendar'),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        CreateEventView.as_view(),
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        EditEventView.as_view(),
        name='edit_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        EventView.as_view(),
        name='event'),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name='delete_event'),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        OccurrenceView.as_view(),
        name='occurrence'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        EditOccurrenceView.as_view(),
        name='edit_occurrence'),

    # urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        OccurrencePreview.as_view(),
        name='occurrence_by_date'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence_by_date'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CreateOccurrenceView.as_view(),
        name='edit_occurrence_by_date'),

    # feed urls
    url(r'^feed/calendar/upcoming/(?P<calendar_id>\d+)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    #url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),

    # api urls
    url(r'^api/occurrences', api_occurrences, name='api_occurrences'),
    url(r'^api/move_or_resize/$',
        api_move_or_resize_by_code,
        name='api_move_or_resize'),
    url(r'^api/select_create/$',
        api_select_create,
        name='api_select_create'),
    url(r'^$', ListView.as_view(queryset=Calendar.objects.all()), name='schedule'),
]

todo/urls.py
from django.urls import path
from django.conf.urls import url
from todo import views

app_name = 'todo'

urlpatterns = [
    path('', views.list_lists, name="lists"),
    # View reorder_tasks is only called by JQuery for drag/drop task ordering.
    path('reorder_tasks/', views.reorder_tasks, name="reorder_tasks"),
    # Allow users to post tasks from outside django-todo (e.g. for filing tickets - see docs)
    path('ticket/add/', views.external_add, name="external_add"),
    # Three paths into `list_detail` view
    path('mine/', views.list_detail, {'list_slug': 'mine'}, name="mine"),
    path('<int:list_id>/<str:list_slug>/completed/', views.list_detail, {'view_completed': True}, name='list_detail_completed'),
    path('<int:list_id>/<str:list_slug>/', views.list_detail, name='list_detail'),
    path('<int:list_id>/<str:list_slug>/delete/', views.del_list, name="del_list"),
    path('add_list/<int:proj>/<int:scop>', views.add_list, name="add_list"),
    path('task/<int:task_id>/', views.task_detail, name='task_detail'),
    path('toggle_done/<int:task_id>/', views.toggle_done, name='task_toggle_done'),
    path('delete/<int:task_id>/', views.delete_task, name='delete_task'),
    path('search/', views.search, name="search"),
]

project/templates/scope/base_scope.html
{% extends "home/base.html" %}

{% block title %}<title>Scope of work</title>{% endblock %}
{% block breadcrumb %} / <a href="{% url 'scope-of-work' %}">Scope of work</a> / {% endblock %}

{% block content %}

{% endblock %}

project/templates/scope/scope_detail.html
{% extends "home/base.html" %}

{% load static %}
{% block title %}<title>Scope of work</title>{% endblock %}
{% block breadcrumb %} / <a href="{% url 'scope-of-work' %}">Scope of work</a>
  {% if request.user.staff %} /<a href="{% url 'create-scope-of-work' proj=scope_detail.project.job_num %}"> add a new scope area</a>{% else %}{% endif %} {% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-8">  
    <div class="card mb-3">
      <div class="card-header" style="background-color:rgb(10, 212, 26);">
        <h4>Scope of work - {{ scope_detail.area }}
          {% if request.user.staff %}
            <div class="add_jobsite"><a href="{% url 'update-scope-of-work' scope_detail.id %}"> edit </a></div>
          {% else %}{% endif %}</h4>
          <b><a href="{% url 'project-detail' scope_detail.project.job_num %}">{{ scope_detail.project.job_num }} - {{scope_detail.project.job_name}} </a></b>
          {% if request.user.staff %}&nbsp; <a href="{% url 'todo:add_list' proj=scope_detail.project.job_num scop=scope_detail.pk %}"> <i class="fa fa-plus-square"></i> add a task list.</a>
          {% else %} There are no task lists in this area, <a href="{% url 'create-scope-of-work' proj=scope_detail.project.job_num %}">please add one.</a>
          {% endif %}
      </div>
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0"> 
          <thead>
            <tr>
              <th style="font-weight: inherit;">Task List </th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th style="font-weight: inherit;">Task List </th>
            </tr>
          </tfoot>
          <tbody>
          {% if task_list %}
            {% for task in task_list %}
              <tr>
                <td>
                  <h5><a href="{% url 'todo:list_detail' task.id task.slug %}"> {{ task.name }}</a></h5>
                </td>
              </tr>
            {% endfor %}
            {% else %}
            <tr>
              <td>
            <p>There are no task lists in this area, <a href="{% url 'todo:add_list' proj=scope_detail.project.job_num scop=scope_detail.pk %}"> <i class="fa fa-plus-square"></i> add a task list.</a></p>
              </td>
            </tr>{% endif %}
          </tbody>
        </table>
      </div> 
    </div>
  </div>
  <div class="col-lg-4">
    <div class="card mb-3">
      <div class="card-header" style="background-color:rgb(0, 119, 255);">
        <h3>Area of work
          {% if request.user.staff %}
            <div class="add_jobsite"><a href="{% url 'create-scope-of-work' proj=scope_detail.project.job_num %}">add</a></div>
          {% else %}
          {% endif %}
        </h3>
      </div>
      <div class="card-body bg-faded">
        {% if other_scopes %}
        <ul>
          {% for others in other_scopes %}
            <li><a href="{% url 'scope-detail' others.id %}"> {{ others.area }} </a></li>
          {% endfor %}
        {% else %}
          <p>There are no areas for this project, please add one.</p>
        {% endif %}
        </ul>
      </div>
    </div>
    <div class="card mb-3">
      <div class="card-header"><b>Devices</b>
        {% if request.user.staff %}
          <a href="{% url 'create-project-device' proj=scope_detail.project.job_num tas=0  %}"><div class="add_jobsite"> + add</div></a>
        {% else %}
        {% endif %}
      </div>
      {% if device_mate_list %}
      <div class="card-body">
        <table>
          {% for device in device_mate_list %}
          <tr width="100%">
            <td width="60%"><a href="{% url 'project-device-detail' device.pk %}"> {{ device.device.general_disc }}</a></td>
            <td>
              {{ device.qty }}
              {% if request.user.staff and request.user.admin %}
              - <a href="{% url 'update-project-device' device.pk %}">edit</a> - ${{ device.total }} 
              {% else %}
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </table><table>
          {% for device in devicelist %}
          <tr width="100%">
            <td width="60%"><a href="{% url 'project-device-detail' device.pk %}"> {{ device.device.general_disc }}</a></td>
            <td>
              {{ device.qty }}
              {% if request.user.staff and request.user.admin %}
              - <a href="{% url 'update-project-device' device.pk %}">edit</a> - ${{ device.total }} 
              {% else %}
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </table>
      </div>
      {% else %}
      {% endif %}
    </div>
    <div class="card mb-3">
      <div class="card-header"><b>Wire</b>
        {% if request.user.staff %}
          <a href="{% url 'create-project-wire' proj=scope_detail.project.job_num tas=0  %}"><div class="add_jobsite"> + add</div></a>
        {% else %}
        {% endif %}
      </div>
      {% if wire_mate_list %}
      <div class="card-body">
        <table>
          {% for wire in wire_mate_list %}
          <tr width="100%">
            <td width="60%"><a href="{% url 'project-wire-detail' wire.pk %}"> {{ wire.wire.general_disc }}</a></td>
            <td>
              {{ wire.length }}
              {% if request.user.staff and request.user.admin %}
                - <a href="{% url 'update-project-wire' wire.pk %}">edit</a> - ${{ wire.total }} 
              {% else %}
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </table>
      </div>
      {% else %}
      {% endif %}
    </div>
    <div class="card mb-3">
      <div class="card-header"><b>Hardware</b>
        {% if request.user.staff %}
          <a href="{% url 'create-project-hardware' proj=scope_detail.project.job_num tas=0  %}"><div class="add_jobsite"> + add</div></a>
        {% else %}
        {% endif %}
      </div>
      {% if hardware_mate_list %}
      <div class="card-body">
        <table>
          {% for hardware in hardware_mate_list %}
          <tr width="100%">
            <td width="70%"><a href="{% url 'project-hardware-detail' hardware.pk %}"> {{ hardware.hardware.general_disc }}</a></td>
            <td>
              {{ hardware.qty }}
              {% if request.user.staff and request.user.admin %}
                - <a href="{% url 'update-project-hardware' hardware.pk %}">edit</a> - ${{ hardware.total }} 
              {% else %}
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </table>
      </div>
      {% else %}
      {% endif %}
    </div>
    <div class="card mb-3">
      <div class="card-header"><b>Software</b>
        {% if request.user.staff %}
          <a href="{% url 'create-project-software' proj=scope_detail.project.job_num tas=0  %}"><div class="add_jobsite"> + add</div></a>
        {% else %}
        {% endif %}
      </div>
      {% if software_mate_list %}
      <div class="card-body">
        <table>
          {% for software in software_mate_list %}
          <tr width="100%">
            <td width="70%"><a href="{% url 'project-software-detail' software.pk %}"> {{ software.software.general_disc }}</a></td>
            <td>
              {{ software.qty }}
              {% if request.user.staff and request.user.admin %}
                - <a href="{% url 'update-project-software' software.pk %}">edit</a> - ${{ software.total }} 
              {% else %}
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </table>
      </div>
      {% else %}
      {% endif %}
    </div>
    <div class="card mb-3">
      <div class="card-header"><b>License</b>
        {% if request.user.staff %}
          <a href="{% url 'create-project-license' proj=scope_detail.project.job_num tas=0  %}"><div class="add_jobsite"> + add</div></a>
        {% else %}
        {% endif %}
      </div>
      {% if license_mate_list %}
      <div class="card-body">
        <table>
          {% for license in license_mate_list %}
          <tr width="100%">
            <td width="70%"><a href="{% url 'project-license-detail' license.pk %}"> {{ license.license.general_disc }}</a></td>
            <td>
              {{ license.qty }}
              {% if request.user.staff and request.user.admin %}
                - <a href="{% url 'update-project-license' license.pk %}">edit</a> - ${{ license.total }} 
              {% else %}
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </table>
      </div>
      {% else %}
      {% endif %}
    </div>
  </div>
</div>
</div>


{% endblock %}

{% block scripter %} 
<script src="{% static 'home/js/sb-admin-datatables.min.js' %}"></script>
<script src="{% static 'home/vendor/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'home/vendor/datatables/dataTables.bootstrap4.js' %}"></script> 
{% endblock %}

project/templates/scope/scopeofwork_confirm_delete.html
{% extends "home/base.html" %}

{% block title %}<title>Delete scope of work</title> {% endblock %}
{% block breadcrumb %} / <a href="{% url 'scope-of-work' %}">Scope of work</a> / Delete scope of work{% endblock %}

{% block content %}

{% if request.user.admin %}
<div class="card mb-3">
  <div class="card-header" style="background-color:rgb(0, 119, 255);">
    <h3>Delete scope of work</h3> 
  </div>
  <form class="form-control" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input style="margin-bottom: 10px;" class="btn btn-primary btn-block" type="submit" value="Confirm">
  </form>
</div>
{% else %}
Your not allowed to view this page..
{% endif %} 
{% endblock %} 

project/templates/scope/scopeofwork_form.html
{% extends "home/base.html" %}

{% block title %}<title>Scope of work creation</title> {% endblock %}
{% block breadcrumb %} / <a href="{% url 'scope-of-work' %}">Scope of work</a> / Create a new scope of work{% endblock %}

{% block content %}

{% if request.user.staff %}
<div class="row">
  <div class="col-lg-6">
    <div class="card mb-3">
      <div class="card-header" style="background-color:rgb(10, 212, 26);">
        <h3>Create a new scope of work</h3> 
      </div>
      <form class="form-control" method="post">{% csrf_token %}
        <div class="form-group">
          <div class="form-row" style="margin-top: 10px;"><label for="id_project">&nbsp; <b>Project:</b></label> {{ form.project.errors }}
              {% if request.user.staff %}<div style="float:right;">&nbsp; <a href="{% url 'create-project-from' jobsi=jobsite %}"> <i class="fa fa-plus-square"></i> create</a></div>{% endif %}
            <select class="form-control" name="project" required="" id="id_project">
                {% for project in form.project %}
                  {{ project }}
                {% endfor %}
            </select>
          </div>
          <div class="form-row" style="margin-top: 10px;">
            <label for="id_area">&nbsp; Area:</label> 
            <input class="form-control" type="text" name="area" id="id_area" maxlength="100" placeholder="area" value="{{ scopeofwork.area }}"></div>
          <div class="form-row" style="margin-top: 10px;">
            <label for="id_system_type">&nbsp; System Type:</label> 
            {{ form.system_type }}</div>
          <div class="form-row" style="margin-top: 10px;">
            <label for="id_system_type">&nbsp; Priority:</label> 
            {{ form.priority }}</div>
        </div>
        <input style="margin-bottom: 10px;" class="btn btn-primary btn-block" type="submit" value="Save" />
      </form>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="card mb-3">
      <div class="card-header" style="background-color:rgb(0, 119, 255);">
        <h3>Whats the Next step?<br>Add devices!</h3> 
      </div> 
    </div>
  </div>
</div>
{% else %}
Your not allowed to view this page..
{% endif %} 
{% endblock %} 

project/templates/scope/scopeofwork_update_form.html
{% extends "home/base.html" %}

{% block title %}<title>Scope of work update</title> {% endblock %}
{% block breadcrumb %} / <a href="{% url 'scope-of-work' %}">Scope of work</a> / Update scope of work{% endblock %}

{% block content %}

{% if request.user.staff %}
<div class="col-lg-6">
  <div class="card mb-3">
    <div class="card-header" style="background-color:rgb(0, 119, 255);">
      <h3>Update scope of work{% if request.user.admin %}<div class="add_jobsite"><a href="{% url 'delete-scope-of-work' scopeofwork.id %}"> delete </a></div>{% else %}{% endif %}</h3>
    </div></div>
    <form class="form-control" method="post">{% csrf_token %}
      <div class="form-group">
        <div class="form-row" style="margin-top: 10px;"><label for="id_project">&nbsp; <b>Project:</b></label> {{ form.project.errors }}
          <select class="form-control" name="project" required="" id="id_project">
              {% for project in form.project %}
                {{ project }}
              {% endfor %}
          </select>
        </div>
        <div class="form-row" style="margin-top: 10px;">
          <label for="id_area">&nbsp; Area:</label> 
          <input class="form-control" type="text" name="area" id="id_area" maxlength="100" placeholder="area" value="{{ scopeofwork.area }}"></div>
        <div class="form-row" style="margin-top: 10px;">
          <label for="id_system_type">&nbsp; System Type:</label> 
          <input class="form-control" type="text" name="system_type" id="id_system_type" maxlength="100" placeholder="system_type" value="{{ scopeofwork.system_type }}"></div>
        </div>
      <input style="margin-bottom: 10px;" class="btn btn-primary btn-block" type="submit" value="Update" />
    </form>
  </div>
</div>
{% else %}
Your not allowed to view this page..
{% endif %} 
{% endblock %} 