home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import contactView, successView

app_name = 'home'
urlpatterns = [
    path('', views.index, name='home'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('contact/', contactView, name='contact'),
    path('success/', successView, name='success'),
    path('send-newsletter/', views.send_newsletter, name='send_newsletter'),
    path('unsubscribe/<str:email>/', views.unsubscribe, name='unsubscribe'),
    path('secret-lab/', views.easter_egg, name='easter_egg'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labmunkznetwork/urls.py
"""labmunkznetwork URL Configuration
"""
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.conf.urls import url

admin.site.site_header = "Labmunkz Network"
admin.site.index_title = "Database administration configuration."

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    #path('api/', include('api.urls')),
    path('group/', include('group.urls')),
    path('munkz/', include('munkz.urls')),
    path("music/", include("music.urls")),
    path("polls/", include("polls.urls")),
    path('shop/', include('shop.urls')),
   # path('asset/', include('asset.urls')),
    path('client/', include('client.urls')),
   # url(r'^filer/', include('filer.urls')),
   # path('helpdesk/', include('helpdesk.urls')),
    path('jobsite/', include('jobsite.urls')),
    path('project/', include('project.urls')),
    path('material/', include('material.urls')),
    path('posts/', include('posts.urls')),
    path('schedule/', include('schedule.urls', namespace='schedule')),
    path('timecard/', include('timecard.urls')),
    path('todo/', include('todo.urls', namespace="todo")),
   # path('wip/', include('wip.urls')),
]
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views

urlpatterns = [
    path(    '',                                  views.ProjectMain,               name='project'),
    path(    'list/',                             views.ProjectListView.as_view(), name='project-list'),
    url(    r'create-project/(?P<jobsi>[0-9]+)$', views.ProjectCreateView,         name='create-project-from'),
    url(    r'update-project/(?P<pk>[0-9]+)/$',   views.ProjectUpdate.as_view(),   name='update-project'),
    url(    r'main/(?P<pk>[0-9]+)/delete/$',      views.ProjectDelete.as_view(),   name='delete-project'),
    re_path(r'^detail/(?P<job_num>\d+)$',         views.ProjectDeView,             name='project-detail'),

    #re_path(r'^project-quote/(?P<job_num>\d+)$',  views.project_quote_view,        name='project-quote'),  
    re_path(r'^render/pdf/(?P<job_num>\d+)$',     views.project_detail_pdf,        name='project-pdf'),
    
    path(    'project-scope/',                 views.ScopeMain,                   name='scope-of-work'),
    url(    r'create-scope/(?P<proj>[0-9]+)$', views.ScopeOfWorkCreateView,       name='create-scope-of-work'),
    re_path(r'^scope/detail/(?P<id>\d+)$',     views.ScopeOfWorkDeView,           name='scope-detail'),
    url(    r'update-scope/(?P<pk>[0-9]+)/$',  views.ScopeOfWorkUpdate.as_view(), name='update-scope-of-work'),
    url(    r'scope/(?P<pk>[0-9]+)/delete/$',  views.ScopeOfWorkDelete.as_view(), name='delete-scope-of-work'),

    path(    'project-device/',                            views.ProjectDevice,                 name='project-device'),
    url(    r'create-device/(?P<proj>\d+)/(?P<tas>\d+)/$', views.ProjectDeviceCreateView,       name='create-project-device'),
    re_path(r'^device-detail/(?P<id>\d+)$',                views.ProjectDeviceDeView,           name='project-device-detail'),
    url(    r'update-device/(?P<pk>[0-9]+)/$',             views.ProjectDeviceUpdate.as_view(), name='update-project-device'),
    url(    r'device/(?P<pk>[0-9]+)/delete/$',             views.ProjectDeviceDelete.as_view(), name='delete-project-device'),

    path(    'project-wire/',                            views.ProjectWire,                 name='project-wire'),
    url(    r'create-wire/(?P<proj>\d+)/(?P<tas>\d+)/$', views.ProjectWireCreateView,       name='create-project-wire'),
    re_path(r'^wire-detail/(?P<id>\d+)$',                views.ProjectWireDeView,           name='project-wire-detail'),
    url(    r'update-wire/(?P<pk>[0-9]+)/$',             views.ProjectWireUpdate.as_view(), name='update-project-wire'),
    url(    r'wire/(?P<pk>[0-9]+)/delete/$',             views.ProjectWireDelete.as_view(), name='delete-project-wire'),

    path(    'project-hardware/',                            views.ProjectHardware,                 name='project-hardware'),
    url(    r'create-hardware/(?P<proj>\d+)/(?P<tas>\d+)/$', views.ProjectHardwareCreateView,       name='create-project-hardware'),
    re_path(r'^hardware-detail/(?P<id>\d+)$',                views.ProjectHardwareDeView,           name='project-hardware-detail'),
    url(    r'update-hardware/(?P<pk>[0-9]+)/$',             views.ProjectHardwareUpdate.as_view(), name='update-project-hardware'),
    url(    r'hardware/(?P<pk>[0-9]+)/delete/$',             views.ProjectHardwareDelete.as_view(), name='delete-project-hardware'),

    path(    'project-software/',                            views.ProjectSoftware,                 name='project-software'),
    url(    r'create-software/(?P<proj>\d+)/(?P<tas>\d+)/$', views.ProjectSoftwareCreateView,       name='create-project-software'),
    re_path(r'^software-detail/(?P<id>\d+)$',                views.ProjectSoftwareDeView,           name='project-software-detail'),
    url(    r'update-software/(?P<pk>[0-9]+)/$',             views.ProjectSoftwareUpdate.as_view(), name='update-project-software'),
    url(    r'software/(?P<pk>[0-9]+)/delete/$',             views.ProjectSoftwareDelete.as_view(), name='delete-project-software'),

    path(    'project-license/',                            views.ProjectLicense,                 name='project-license'),
    url(    r'create-license/(?P<proj>\d+)/(?P<tas>\d+)/$', views.ProjectLicenseCreateView,       name='create-project-license'),
    re_path(r'^license-detail/(?P<id>\d+)$',                views.ProjectLicenseDeView,           name='project-license-detail'),
    url(    r'update-license/(?P<pk>[0-9]+)/$',             views.ProjectLicenseUpdate.as_view(), name='update-project-license'),
    url(    r'license/(?P<pk>[0-9]+)/delete/$',             views.ProjectLicenseDelete.as_view(), name='delete-project-license'),

    path(    'project-travel/',                            views.ProjectTravel,                 name='project-travel'),
    url(    r'create-travel/(?P<proj>\d+)/(?P<tas>\d+)/$', views.ProjectTravelCreateView,       name='create-project-travel'),
    re_path(r'^travel-detail/(?P<id>\d+)$',                views.ProjectTravelDeView,           name='project-travel-detail'),
    url(    r'update-travel/(?P<pk>[0-9]+)/$',             views.ProjectTravelUpdate.as_view(), name='update-project-travel'),
    url(    r'travel/(?P<pk>[0-9]+)/delete/$',             views.ProjectTravelDelete.as_view(), name='delete-project-travel'),
]

schedule/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from django.views.generic.list import ListView
from . import views
#CalendarICalendar, 
from schedule.feeds import UpcomingEventsFeed
from schedule.models import Calendar
from schedule.periods import Day, Month, Week, Year
from schedule.views import (
    CalendarByPeriodsView, CalendarView, CancelOccurrenceView, CreateEventView, EventCreateView,
    CreateOccurrenceView, DeleteEventView, EditEventView, EditOccurrenceView,
    EventView, FullCalendarView, OccurrencePreview, OccurrenceView,
    api_move_or_resize_by_code, api_occurrences, api_select_create, EventTodayArchiveView, EventDayArchiveView,
)
app_name = 'schedule'
urlpatterns = [
    #re_path(r'^detail/schedule/(?P<pk>\d+)$', views.DayEventDetailView.as_view(), name='event-detail'),
    #path('create-event/', views.EventCreate.as_view(), name='create-event'), 
    url(r'create-event/(?P<proj>[0-9]+)$', views.EventCreateView, name='create-event'), 
    #url(r'schedule/update-event/(?P<pk>[0-9]+)/$', views.DayEventUpdate.as_view(), name='update-event'),
    #url(r'schedule/event/(?P<pk>[0-9]+)/delete/$', views.DayEventDelete.as_view(), name='delete-event'),
    path('today/', EventTodayArchiveView.as_view(), name='archive_today'),
    path('<int:year>/<str:month>/<int:day>/', EventDayArchiveView.as_view(), name='archive_day'),

    url(r'^$', ListView.as_view(model=Calendar), name='calendar_list'),

    url(r'^calendar/year/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_year.html'),
        name='year_calendar',
        kwargs={'period': Year}),

    url(r'^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_tri_month.html'),
        name='tri_month_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_compact_month.html'),
        name='compact_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_month.html'),
        name='month_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/week/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_week.html'),
        name='week_calendar',
        kwargs={'period': Week}),

    url(r'^calendar/daily/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_day.html'),
        name='day_calendar',
        kwargs={'period': Day}),

    url(r'^calendar/(?P<calendar_slug>[-\w]+)/$',
        CalendarView.as_view(),
        name='calendar_home',
        ),
    url(r'^fullcalendar/(?P<calendar_slug>[-\w]+)/$',
        FullCalendarView.as_view(),
        name='fullcalendar'),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        CreateEventView.as_view(),
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        EditEventView.as_view(),
        name='edit_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        EventView.as_view(),
        name='event'),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name='delete_event'),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        OccurrenceView.as_view(),
        name='occurrence'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        EditOccurrenceView.as_view(),
        name='edit_occurrence'),

    # urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        OccurrencePreview.as_view(),
        name='occurrence_by_date'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence_by_date'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CreateOccurrenceView.as_view(),
        name='edit_occurrence_by_date'),

    # feed urls
    url(r'^feed/calendar/upcoming/(?P<calendar_id>\d+)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    #url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),

    # api urls
    url(r'^api/occurrences', api_occurrences, name='api_occurrences'),
    url(r'^api/move_or_resize/$',
        api_move_or_resize_by_code,
        name='api_move_or_resize'),
    url(r'^api/select_create/$',
        api_select_create,
        name='api_select_create'),
    url(r'^$', ListView.as_view(queryset=Calendar.objects.all()), name='schedule'),
]

todo/forms.py
from django import forms
from django.contrib.auth.models import User, Group 
from django.forms import ModelForm
from todo.models import Task, TaskList
from project.models import Project, ScopeOfWork


class AddTaskListForm(ModelForm):
    """The picklist showing allowable groups to which a new list can be added
    determines which groups the user belongs to. This queries the form object
    to derive that list."""
    
    def __init__(self, user, proj, *args, **kwargs):
        super(AddTaskListForm, self).__init__(*args, **kwargs)
        self.fields["group"].queryset = Group.objects.filter(artist=user)
        self.fields["group"].widget.attrs = {
            "id": "id_group",
            "class": "custom-select mb-3",
            "name": "group",
        }
        self.fields["scope"].queryset = ScopeOfWork.objects.all().filter(project__job_num=proj)
        self.fields["scope"].widget.attrs = {
            "id": "id_scope",
            "class": "custom-select mb-3",
            "name": "scope",
        }
        self.fields["priority"].widget.attrs = {
            "id": "id_priority",
            "class": "custom-select mb-3",
            "name": "priority",
        }

    class Meta:
        model = TaskList
        exclude = ["created_date", "slug"]
        

class AddEditTaskForm(ModelForm):
    """The picklist showing the users to which a new task can be assigned
    must find other members of the group this TaskList is attached to."""

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        task_list = kwargs.get("initial").get("task_list")
        members = task_list.group.artist_set.all()
        self.fields["assigned_to"].queryset = members
        self.fields["assigned_to"].label_from_instance = lambda obj: "%s (%s)" % (
            obj.get_full_name(),
            obj.email,
        )
        self.fields["assigned_to"].widget.attrs = {
            "id": "id_assigned_to",
            "class": "custom-select mb-3",
            "name": "assigned_to",
        }
        self.fields["position"].widget.attrs = {
            "id": "position",
            "class": "custom-select mb-3",
            "name": "position",
        }
        self.fields["task_list"].value = kwargs["initial"]["task_list"].id

    due_date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}), required=False)

    title = forms.CharField(widget=forms.widgets.TextInput())

    note = forms.CharField(widget=forms.Textarea(), required=False)

    class Meta:
        model = Task
        exclude = []


class AddExternalTaskForm(ModelForm):
    """Form to allow users who are not part of the GTD system to file a ticket."""

    title = forms.CharField(widget=forms.widgets.TextInput(attrs={"size": 35}), label="Summary")
    note = forms.CharField(widget=forms.widgets.Textarea(), label="Problem Description")
    priority = forms.IntegerField(widget=forms.HiddenInput())

    class Meta:
        model = Task
        exclude = (
            "task_list",
            "created_date",
            "due_date",
            "created_by",
            "assigned_to",
            "position",
            "completed",
            "completed_date",
        )


class SearchForm(forms.Form):
    """Search."""

    q = forms.CharField(widget=forms.widgets.TextInput(attrs={"size": 35}))

project/templates/project/base_project.html
{% extends "home/base.html" %}
{% load static %}
{% block title %}<title>Project List</title>{% endblock %}
{% block styler %}<link href="{% static 'home/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet" type="text/css"> {% endblock %}
{% block breadcrumb %} / <a href="{% url 'jobsite-list' %}">Job Site</a> / <a href="{% url 'project-list' %}">Project</a> / list{% endblock %}
{% block content %}
<!-- Example DataTables Card-->
<div class="card mb-3">
    <div class="table-responsive">
      <table class="table table-bordered"width="100%" cellspacing="0">
        <thead>
          <tr>
            <th style="font-weight: inherit;">Clients: Map of Sites?</th>
            <th style="font-weight: inherit;">Jobs: </th>
            <th style="font-weight: inherit;">Jobs Open: </th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th style="font-weight: inherit;">Clients: </th>
            <th style="font-weight: inherit;">Jobs: </th>
            <th style="font-weight: inherit;">Jobs Open: </th>
          </tr>
        </tfoot>
        <tbody>  
          <tr>
            <td>{{ num_clients }}</td>
            <td>{{ num_jobs }} </td>
            <td>{{ num_jobs_open }} </td>
          </tr>
        </tbody>
      </table>
    </div>
</div>  
{% endblock %}

{% block scripter %} 
<script src="{% static 'home/js/sb-admin-datatables.min.js' %}"></script>
<script src="{% static 'home/vendor/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'home/vendor/datatables/dataTables.bootstrap4.js' %}"></script> 
{% endblock %}

project/templates/project/project_confirm_delete.html
{% extends "home/base.html" %}

{% block title %}<title>Project info Delete</title> {% endblock %}
{% block breadcrumb %} / <a href="{% url 'jobsite-list' %}">Job Site</a> / <a href="{% url 'project-list' %}">Project</a> / Delete project info{% endblock %}

{% block content %}

{% if request.user.admin %}
  <div class="card mb-3">
    <div class="card-header" style="background-color:rgb(0, 119, 255);">
      <h3>Delete project info</h3> 
    </div>
    <form class="form-control" ethod="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ object }}"?</p>
      <input style="margin-bottom: 10px;" class="btn btn-primary btn-block" type="submit" value="Confirm">
  </form>
  </div>
{% else %}
Your not allowed to view this page..
{% endif %} 
{% endblock %} 

project/templates/project/project_form.html
{% extends "home/base.html" %}

{% block title %}<title>Project Creation</title> {% endblock %}

{% block breadcrumb %} / <a href="{% url 'jobsite-list' %}">Job Site</a> / <a href="{% url 'project-list' %}">Project</a> / Create a new project{% endblock %}

{% block content %} {% if request.user.staff %}
<div class="row">
 <div class="col-lg-6">
  <div class="card mb-3">
    <div class="card-header" style="background-color:rgb(255, 219, 57);">
      <h3>Create a new Project</h3> 
    </div>
    {{ form.non_field_errors }}
    <form class="form-control" method="post" >{% csrf_token %}
      <div class="form-group">
        <div class="form-row">
         <div class="col-3">
          <label for="id_job_num">&nbsp; <b>Job num:</b></label> {{ form.job_num.errors }}
            <input class="form-control" type="number" name="job_num" id="id_job_num" required="" value="{{ project.job_num }}" placeholder="####">
         </div>
         <div class="col">
          <label for="id_job_name">&nbsp; <b>Job name:</b></label> {{ form.job_name.errors }}
            <input class="form-control" type="text" name="job_name" id="id_job_name" maxlength="200" required="" value="{{ project.job_name }}" placeholder="Job Name">
         </div>
         <div class="col">
          <label for="id_job_name">&nbsp; Revision:</label> {{ form.revision.errors }}
            <input class="form-control" type="text" name="revision" id="id_revision" maxlength="200" value="" placeholder="Number or Name">
         </div>
        </div>
        <div class="form-row" style="margin-top: 10px;">
         <div class="col">
          <label for="id_jobsite"><b>&nbsp; Jobsite:</b></label> 
          {{ form.jobsite.errors }}{% if request.user.staff %}<div style="float:right;">&nbsp; <a href="{% url 'create-jobsite-from' client=client %}"> <i class="fa fa-plus-square"></i> create</a></div>{% endif %}
          {{ form.jobsite }}
         </div>
         <div class="col">
          <label for="id_job_status">&nbsp; Job status:</label> {{ form.job_status.errors }}
          <select class="form-control" name="job_status" id="id_job_status">
            {% for job_status in form.job_status %}
            {{ job_status }}
            {% endfor %} 
          </select>
         </div> 
        </div>
        <div class="form-row" style="margin-top: 10px;">
          <label for="id_install_overview">&nbsp; Install overview:</label> {{ form.install_overview.errors }}
          <textarea class="form-control" name="install_overview" cols="40" maxlength="8000" id="id_install_overview" rows="10" placeholder="Enter the overview of the install">{{ project.install_overview }}</textarea>
        </div>
        <div class="form-row" style="margin-top: 10px;">
          <label for="id_pricing_disclaim">&nbsp; Price Policy:</label> {{ form.pricing_disclaim.errors }}
          <textarea class="form-control" name="pricing_disclaim" cols="40" maxlength="8000" id="id_pricing_disclaim" rows="10" placeholder="Enter the overview of the install">{{ project.pricing_disclaim }}</textarea>
        </div>
        <div class="form-row" style="margin-top: 10px;">
          <label for="id_site_contact">&nbsp; Site Contact:</label> {{ form.site_contact.errors }}
          <input class="form-control" name="site_contact" type="text" id="id_site_contact" value="{{ project.site_contact }}" placeholder="Joe Shmoe">
        </div>
        <div class="form-row" style="margin-top: 10px;">
          <label for="id_date_requested">&nbsp; <b>Start date requested:</b></label> {{ form.date_requested.errors }}
          <input class="form-control" type="date" name="date_requested" id="id_date_requested" required="" value="{{ project.date_requested|date:"Y-m-d" }}" aria-describedby="nameHelp">
        </div>
        <hr>
        <div class="form-row">
          <div class="col" style="margin-top: 10px;">
            <label for="id_due_date">&nbsp; Due date:</label> {{ form.due_date.errors }}
            <input class="form-control" type="date" name="due_date" id="id_due_date" value="{{ project.due_date|date:"Y-m-d" }}" aria-describedby="nameHelp">
          </div>
          <div class="col" style="margin-top: 10px;">
            <label for="id_finished_date">&nbsp; Finished date:</label> {{ form.finished_date.errors }}
            <input class="form-control" type="date" name="finished_date" id="id_finished_date" value="{{ project.finished_date|date:"Y-m-d" }}" aria-describedby="nameHelp">
          </div>
          <div class="col" style="margin-top: 10px;">
            <label for="id_paid_date">&nbsp; Paid date:</label> {{ form.paid_date.errors }}
            <input class="form-control" type="date" name="paid_date" id="id_paid_date" value="{{ project.paid_date|date:"Y-m-d" }}" aria-describedby="nameHelp">
          </div>
        </div>
        <div class="form-row" style="margin-top: 10px;">
          <div class="col"> 
            <label for="id_tax_status">&nbsp; Tax status:</label> {{ form.tax_status.errors }}
            <select class="form-control" name="tax_status" id="id_tax_status">
              {% for tax_status in form.tax_status %}
              {{ tax_status }}
              {% endfor %} 
            </select>
          </div>
          <div class="col"> 
            <label for="id_type_status">&nbsp; Type status:</label> {{ form.type_status.errors }}
            <select class="form-control" name="type_status" id="id_type_status">
              {% for type_status in form.type_status %}
              {{ type_status }}
              {% endfor %} 
            </select>
          </div>
        </div>
      </div>
    </div>  
  </div>
  <div class="col-lg-6">
    <div class="card mb-3">
      <div class="card-body">
        <div class="form-group">
          <div class="form-row" style="margin-top: 10px;">
            <div class="col">
              <label for="id_division_status">&nbsp; Division status:</label> {{ form.division_status.errors }}
              <select class="form-control" name="division_status" id="id_division_status">
                {% for division_status in form.division_status %}
                {{ division_status }}
                {% endfor %} 
              </select>
            </div>
            <div class="col">
              <label for="id_foremen">&nbsp; Foremen:</label> {{ form.foremen.errors }}
              <select class="form-control" name="foremen" id="id_foremen">
                {% for foremen in form.foremen %}
                {{ foremen }}
                {% endfor %} 
              </select>
            </div>
          </div>
          <div class="form-row" style="margin-top: 10px;"> 
            <div class="col">
              <label for="id_estimator">&nbsp; Estimator:</label> {{ form.estimator.errors }}
              <select class="form-control" name="estimator" id="id_estimator">
                {% for estimator in form.estimator %}
                  {{ estimator }}
                {% endfor %} 
              </select>
            </div>
            <div class="col">
              <label for="id_projectmanager">&nbsp; Project manager:</label> {{ form.projectmanager.errors }}
              <select class="form-control" name="projectmanager" id="id_projectmanager">
                {% for projectmanager in form.projectmanager %}
                {{ projectmanager }}
                {% endfor %} 
              </select>
            </div>
          </div>
          <div class="form-row" style="margin-top: 10px;">
            <label for="id_lead">&nbsp; Lead:</label> {{ form.lead.errors }}
            <select class="form-control" name="lead" id="id_lead" multiple="">
              {% for lead in form.lead %}
              {{ lead }}
              {% endfor %} 
            </select>
          </div>
          <div class="form-row" style="margin-top: 10px;">
            <label for="id_artist">&nbsp; Artists:</label> {{ form.artist.errors }}
            <select class="form-control" name="artist" id="id_artist" multiple="">
              {% for artist in form.artist %}
                {{ artist }}
              {% endfor %}
            </select>
          </div>
          <div class="form-row" style="margin-top: 10px;">
            <div class="col">
              <label for="id_burden">&nbsp; <b>Burden Percentage:</b></label> {{ form.burden.errors }}
              <input class="form-control" type="number" name="burden" required="" placeholder="1.65" step="0.01" id="id_burden" value="{{ project.burden }}">
            </div>
            <div class="col">
              <label for="id_markup">&nbsp; <b>Material Markup:</b></label> {{ form.markup.errors }}
              <input class="form-control" type="number" name="markup" required="" placeholder="1.15" step="0.01" id="id_markup" value="{{ project.markup }}">
            </div> 
            <div class="col">
              <label for="id_licmarkup">&nbsp; <b>License Markup:</b></label> {{ form.licmarkup.errors }}
              <input class="form-control" type="number" name="licmarkup" required="" placeholder="1.15" step="0.01" id="id_licmarkup" value="{{ project.licmarkup }}">
            </div>
        </div> 
        </div>  
          <div class="form-row" style="margin-top: 10px;">
            <div class="col">
              <label for="id_estimated_cost">&nbsp; <b>Estimated cost:</b></label> {{ form.estimated_cost.errors }}
              <input class="form-control" type="number" name="estimated_cost" required="" placeholder="4000.00" step="0.01" id="id_estimated_cost" value="{{ project.estimated_cost }}">
            </div>
            <div class="col">
              <label for="id_contract_value">&nbsp; <b>Contract value:</b></label> {{ form.contract_value.errors }}
              <input class="form-control" type="number" name="contract_value" required="" placeholder="4500.00" step="0.01" id="id_contract_value" value="{{ project.contract_value }}">
            </div>
          </div>                  
        </div>
        <input style="margin-bottom: 10px;" class="btn btn-primary btn-block" type="submit" value="Save" />
        </div>
      </div>
    </form> 
    </div>
    <div class="col-lg-6">
      <div class="card mb-3">
        Whats the Next step?<br>
        Create a Task mate! 
      </div>
    </div>
  </div>
</div>
{% else %}
Your not allowed to view this page..
{% endif %} 
{% endblock %} 