home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import contactView, successView

app_name = 'home'
urlpatterns = [
    path('', views.index, name='home'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('contact/', contactView, name='contact'),
    path('success/', successView, name='success'),
    path('send-newsletter/', views.send_newsletter, name='send_newsletter'),
    path('unsubscribe/<str:email>/', views.unsubscribe, name='unsubscribe'),
    path('secret-lab/', views.easter_egg, name='easter_egg'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labmunkznetwork/urls.py
"""labmunkznetwork URL Configuration
"""
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.conf.urls import url

admin.site.site_header = "Labmunkz Network"
admin.site.index_title = "Database administration configuration."

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    #path('api/', include('api.urls')),
    path('group/', include('group.urls')),
    path('munkz/', include('munkz.urls')),
    path("music/", include("music.urls")),
    path("polls/", include("polls.urls")),
    path('shop/', include('shop.urls')),
   # path('asset/', include('asset.urls')),
    path('client/', include('client.urls')),
   # url(r'^filer/', include('filer.urls')),
   # path('helpdesk/', include('helpdesk.urls')),
    path('jobsite/', include('jobsite.urls')),
    path('project/', include('project.urls')),
    path('material/', include('material.urls')),
    path('posts/', include('posts.urls')),
    path('schedule/', include('schedule.urls', namespace='schedule')),
    path('timecard/', include('timecard.urls')),
    path('todo/', include('todo.urls', namespace="todo")),
   # path('wip/', include('wip.urls')),
]
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schedule/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from django.views.generic.list import ListView
from . import views
#CalendarICalendar, 
from schedule.feeds import UpcomingEventsFeed
from schedule.models import Calendar
from schedule.periods import Day, Month, Week, Year
from schedule.views import (
    CalendarByPeriodsView, CalendarView, CancelOccurrenceView, CreateEventView, EventCreateView,
    CreateOccurrenceView, DeleteEventView, EditEventView, EditOccurrenceView,
    EventView, FullCalendarView, OccurrencePreview, OccurrenceView,
    api_move_or_resize_by_code, api_occurrences, api_select_create, EventTodayArchiveView, EventDayArchiveView,
)
app_name = 'schedule'
urlpatterns = [
    #re_path(r'^detail/schedule/(?P<pk>\d+)$', views.DayEventDetailView.as_view(), name='event-detail'),
    #path('create-event/', views.EventCreate.as_view(), name='create-event'), 
    url(r'create-event/(?P<proj>[0-9]+)$', views.EventCreateView, name='create-event'), 
    #url(r'schedule/update-event/(?P<pk>[0-9]+)/$', views.DayEventUpdate.as_view(), name='update-event'),
    #url(r'schedule/event/(?P<pk>[0-9]+)/delete/$', views.DayEventDelete.as_view(), name='delete-event'),
    path('today/', EventTodayArchiveView.as_view(), name='archive_today'),
    path('<int:year>/<str:month>/<int:day>/', EventDayArchiveView.as_view(), name='archive_day'),

    url(r'^$', ListView.as_view(model=Calendar), name='calendar_list'),

    url(r'^calendar/year/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_year.html'),
        name='year_calendar',
        kwargs={'period': Year}),

    url(r'^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_tri_month.html'),
        name='tri_month_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_compact_month.html'),
        name='compact_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_month.html'),
        name='month_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/week/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_week.html'),
        name='week_calendar',
        kwargs={'period': Week}),

    url(r'^calendar/daily/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_day.html'),
        name='day_calendar',
        kwargs={'period': Day}),

    url(r'^calendar/(?P<calendar_slug>[-\w]+)/$',
        CalendarView.as_view(),
        name='calendar_home',
        ),
    url(r'^fullcalendar/(?P<calendar_slug>[-\w]+)/$',
        FullCalendarView.as_view(),
        name='fullcalendar'),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        CreateEventView.as_view(),
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        EditEventView.as_view(),
        name='edit_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        EventView.as_view(),
        name='event'),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name='delete_event'),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        OccurrenceView.as_view(),
        name='occurrence'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        EditOccurrenceView.as_view(),
        name='edit_occurrence'),

    # urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        OccurrencePreview.as_view(),
        name='occurrence_by_date'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence_by_date'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CreateOccurrenceView.as_view(),
        name='edit_occurrence_by_date'),

    # feed urls
    url(r'^feed/calendar/upcoming/(?P<calendar_id>\d+)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    #url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),

    # api urls
    url(r'^api/occurrences', api_occurrences, name='api_occurrences'),
    url(r'^api/move_or_resize/$',
        api_move_or_resize_by_code,
        name='api_move_or_resize'),
    url(r'^api/select_create/$',
        api_select_create,
        name='api_select_create'),
    url(r'^$', ListView.as_view(queryset=Calendar.objects.all()), name='schedule'),
]

todo/urls.py
from django.urls import path
from django.conf.urls import url
from todo import views

app_name = 'todo'

urlpatterns = [
    path('', views.list_lists, name="lists"),
    # View reorder_tasks is only called by JQuery for drag/drop task ordering.
    path('reorder_tasks/', views.reorder_tasks, name="reorder_tasks"),
    # Allow users to post tasks from outside django-todo (e.g. for filing tickets - see docs)
    path('ticket/add/', views.external_add, name="external_add"),
    # Three paths into `list_detail` view
    path('mine/', views.list_detail, {'list_slug': 'mine'}, name="mine"),
    path('<int:list_id>/<str:list_slug>/completed/', views.list_detail, {'view_completed': True}, name='list_detail_completed'),
    path('<int:list_id>/<str:list_slug>/', views.list_detail, name='list_detail'),
    path('<int:list_id>/<str:list_slug>/delete/', views.del_list, name="del_list"),
    path('add_list/<int:proj>/<int:scop>', views.add_list, name="add_list"),
    path('task/<int:task_id>/', views.task_detail, name='task_detail'),
    path('toggle_done/<int:task_id>/', views.toggle_done, name='task_toggle_done'),
    path('delete/<int:task_id>/', views.delete_task, name='delete_task'),
    path('search/', views.search, name="search"),
]

todo/models.py
from __future__ import unicode_literals
import datetime
from django.utils.text import slugify

from django.conf import settings
from django.contrib.auth.models import Group
from django.db import models
from django.urls import reverse
from django.utils import timezone
from datetime import date
#from hr.models import PositionPay

class TaskList(models.Model):
    name = models.CharField(max_length=200)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    scope = models.ForeignKey('project.ScopeOfWork', on_delete=models.CASCADE, null=True, related_name="scopets")
    priority = models.PositiveIntegerField(default='9999', help_text='Priorty')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name + self.scope + self.group + self.pk)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Task Lists"

        # Prevents (at the database level) creation of two lists with the same slug in the same group
        unique_together = ("group", "slug")


class Task(models.Model):
    title = models.CharField(max_length=140)
    task_list = models.ForeignKey('TaskList', on_delete=models.CASCADE, null=True)
    created_date = models.DateField(default=timezone.now, blank=True, null=True)
    
    allotted_time = models.DecimalField(max_digits=18, decimal_places=2, default='0.25', blank=True, null=True, help_text='How long would it take')
    team_size     = models.PositiveIntegerField(default='1', help_text='Team size') 
    def ext_hours(self):
        return self.allotted_time * self.team_size
    total_hours = property(ext_hours)
    
    due_date = models.DateField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    completed_date = models.DateField(blank=True, null=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="todo_created_by", on_delete=models.CASCADE
    )
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        related_name="todo_assigned_to",
        on_delete=models.CASCADE,
    )
    #position = models.ForeignKey(PositionPay, on_delete=models.CASCADE, null=True, related_name="pos", help_text='Select position')
    note = models.TextField(blank=True, null=True)
    priority = models.PositiveIntegerField()

    # Has due date for an instance of this object passed?
    def overdue_status(self):
        "Returns whether the Tasks's due date has passed or not."
        if self.due_date and datetime.date.today() > self.due_date:
            return True

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("todo:task_detail", kwargs={"task_id": self.id})

    # Auto-set the Task creation / completed date
    def save(self, **kwargs):
        # If Task is being marked complete, set the completed_date
        if self.completed:
            self.completed_date = datetime.datetime.now()
        super(Task, self).save()

    class Meta:
        ordering = ["priority"]


class Comment(models.Model):
    """
    Not using Django's built-in comments because we want to be able to save
    a comment and change task details at the same time. Rolling our own since it's easy.
    """

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="todo_comments")
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.datetime.now)
    body = models.TextField(blank=True)

    def snippet(self):
        # Define here rather than in __str__ so we can use it in the admin list_display
        return "{author} - {snippet}...".format(author=self.author, snippet=self.body[:35])

    def __str__(self):
        return self.snippet()

todo/views/add_list.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.text import slugify
from project.models import Project
from todo.forms import AddTaskListForm
from todo.utils import staff_check

@login_required
@user_passes_test(staff_check)
def add_list(request, proj, scop) -> HttpResponse:
    """Allow users to add a new todo list to the group they're in.
    """
    # Only staffers can add lists, regardless of TODO_STAFF_USER setting.
    if not request.user.is_staff:
        raise PermissionDenied

    if request.POST:
        form = AddTaskListForm(request.user, proj, request.POST)
        if form.is_valid():
            try:
                newlist = form.save(commit=False)
                newlist.slug = slugify(newlist.name)
                newlist.save()
                messages.success(request, "A new list has been added.")
                return HttpResponseRedirect('/project/scope/detail/'+str(scop))

            except IntegrityError:
                messages.warning(
                    request,
                    "There was a problem saving the new list. "
                    "Most likely a list with the same name in the same group already exists.",
                )
    else:
        if request.user.groups.all().count() == 1:
            # FIXME: Assuming first of user's groups here; better to prompt for group
            form = AddTaskListForm(request.user, proj, initial={"group": request.user.groups.all()[0], "scope":scop})
        else:
            form = AddTaskListForm(request.user, proj, initial={"scope":scop})

    context = {"form": form,
               "proj":proj}

    return render(request, "todo/add_list.html", context)

todo/views/del_list.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from todo.models import Task, TaskList
from todo.utils import staff_check


@login_required
@user_passes_test(staff_check)
def del_list(request, list_id: int, list_slug: str) -> HttpResponse:
    """Delete an entire list. Only staff members should be allowed to access this view.
    """
    task_list = get_object_or_404(TaskList, id=list_id)

    # Ensure user has permission to delete list. Get the group this list belongs to,
    # and check whether current user is a member of that group AND a staffer.
    if task_list.group not in request.user.groups.all() and not request.user.is_staff:
        raise PermissionDenied

    if request.method == "POST":
        TaskList.objects.get(id=task_list.id).delete()
        messages.success(request, "{list_name} is gone.".format(list_name=task_list.name))
        return redirect("todo:lists")
    else:
        task_count_done = Task.objects.filter(task_list=task_list.id, completed=True).count()
        task_count_undone = Task.objects.filter(task_list=task_list.id, completed=False).count()
        task_count_total = Task.objects.filter(task_list=task_list.id).count()

    context = {
        "task_list": task_list,
        "task_count_done": task_count_done,
        "task_count_undone": task_count_undone,
        "task_count_total": task_count_total,
    }

    return render(request, "todo/del_list.html", context)

todo/views/delete_task.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse

from todo.models import Task
from todo.utils import staff_check


@login_required
@user_passes_test(staff_check)
def delete_task(request, task_id: int) -> HttpResponse:
    """Delete specified task.
    Redirect to the list from which the task came.
    """

    if request.method == "POST":
        task = get_object_or_404(Task, pk=task_id)

        redir_url = reverse(
            "todo:list_detail",
            kwargs={"list_id": task.task_list.id, "list_slug": task.task_list.slug},
        )

        # Permissions
        if not (
            (task.created_by == request.user)
            or (request.user.is_superuser)
            or (task.assigned_to == request.user)
            or (task.task_list.group in request.user.groups.all())
        ):
            raise PermissionDenied

        task.delete()

        messages.success(request, "Task '{}' has been deleted".format(task.title))
        return redirect(redir_url)

    else:
        raise PermissionDenied

todo/templates/todo/add_list.html
{% extends "todo/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}<title>Add Todo List</title>{% endblock %}

{% block breadcrumb %} / <a href="{% url 'jobsite-list' %}">Job Site</a> / <a href="{% url 'project-list' %}">Project</a> / To Do List creation
{% endblock %}

{% block content %}
  
  <h2>Add a list to <a href="{% url 'project-detail' proj %}">Project: {{ proj }} </a></h2>

  <form action="" method="post">
    {% csrf_token %}

    <div class="form-group">
      <label for="id_name">List Name</label>
      <input type="text" class="form-control" id="id_name" name="name" aria-describedby="inputNameHelp" placeholder="">
      <small id="inputNameHelp" class="form-text text-muted">The full display name for this list.</small>
    </div>
    <div class="form-group">
      <label for="id_group">Group</label>
      {{form.group}}
    </div>
    <div class="form-group">
      <label for="id_scope">Project Scope</label>
        {% if request.user.staff %}&nbsp; <a href="{% url 'create-scope-of-work' proj=proj %}"> <i class="fa fa-plus-square"></i> create</a>{% endif %}
      {{form.scope}}
    </div>
    <div class="form-group">
      <label for="id_priority">Priority</label>
      {{form.priority}}
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

todo/templates/todo/add_task_external.html
{% extends "todo/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}<title>File Ticket</title>{% endblock %}

{% block content %}

  <h2>{{ task }}</h2>

  <form action="" method="POST">
    {% csrf_token %}

    <h3>File Trouble Ticket</h3>
    <p>
      Have a support issue? Use this form to report the difficulty - we'll get right back to you.
    </p>

    {% if form.errors %}
      {% for error in form.errors %}
        <ul class="errorlist">
          <li>
            <strong>The {{ error|escape }} field is required.</strong>
          </li>
        </ul>
      {% endfor %}
    {% endif %}

    <form action="" name="add_task" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_title" name="title">Subject</label>
          <input type="text" class="form-control" id="id_title" name="title" required placeholder="Our spaceship doesn't go"
            value="{% if form.title.value %}{{ form.title.value }}{% endif %}">
        </div>
        <div class="form-group">
          <label for="id_note">Description</label>
          <textarea class="form-control" id="id_note" name="note" rows="5"
            aria-describedby="inputNoteHelp">{% if form.note.value %}{{ form.note.value }}{% endif %}</textarea>
          <small id="inputNoteHelp" class="form-text text-muted">
            Describe the issue. Please include essential details.
          </small>
        </div>

        <input type="hidden" id="id_priority" name="priority" value="50">
        <p><input type="submit" class="btn btn-primary" name="add_task" value="Submit"></p>
    </form>

{% endblock %}

todo/templates/todo/base.html
{% extends "home/base.html" %}
{% load static %}

{% block extrahead %}
	<!-- CSS and JavaScripts for django-todo -->
	<link rel="stylesheet" type="text/css" href="{% static 'todo/css/styles.css' %}" />
{% endblock extrahead %}

todo/templates/todo/del_list.html
{% extends "todo/base.html" %}
{% block title %}<title>Delete list</title>{% endblock %}

{% block content %}
  {% if user.is_staff %}
  <h1>Delete entire list: {{ task_list.name }} ?</h1>

  <p>Category tally:</p>

  <ul>
    <li>Incomplete: {{ task_count_undone }} </li>
    <li>Complete: {{ task_count_done }} </li>
    <li>
      <strong>Total: {{ task_count_total }}</strong>
    </li>
  </ul>

  <p> ... all of which will be irretrievably
    <strong>blown away</strong>. Are you sure you want to do that?</p>

  <form action="" method="post" accept-charset="utf-8">
    {% csrf_token %}
    <input type="hidden" name="task_list" value="{{ task_list.id }}">
    <p>
      <a href="{% url 'todo:list_detail' task_list.id task_list.slug %}" class="btn btn-success">Return to list: {{ task_list.name }}</a>
      <input type="submit" name="delete-confirm" value="Do it! &rarr;" class="btn btn-danger">
    </p>
  </form>


{% else %}
  <p>Sorry, you don't have permission to delete lists. Please contact your group administrator.</p>
{% endif %} {% endblock %}

todo/templates/todo/list_detail.html
{% extends "todo/base.html" %}
{% load static %}

{% block title %}<title>Todo List: {{ task_list.name }}</title>
{% endblock %}

{% block breadcrumb %} / <a href="{% url 'jobsite-list' %}">Job Site</a> / <a href="{% url 'project-list' %}">Project</a> / To Do List
{% endblock %}

{% block content %}

  {% if list_slug != "mine" %}
    <button class="btn btn-primary" id="AddTaskButton" type="button"
      data-toggle="collapse" data-target="#AddEditTask">Add Task</button>

    {# Task edit / new task form #}
    {% include 'todo/include/task_edit.html' %}
    <hr />
  {% endif %}

  {% if tasks %}
    {% if list_slug == "mine" %}
      <h5>Tasks assigned to me (in all groups)</h5>
    {% else %}
      <h5>{{ view_completed|yesno:"Completed tasks, Tasks" }} in "{{ task_list.name }}"</h5>
      <h5><a href="{{ task_list.scope.project.get_absolute_url }}">{{ task_list.scope.project.job_num }} - {{ task_list.scope.project.job_name }} - {{ task_list.scope.project.jobsite }}</a></h5>
      <p><small><i>In workgroup "{{ task_list.group }}" - drag rows to set priorities.</i></small></p>
    {% endif %}

      <table class="table" id="tasktable">
        <tr class="nodrop">
          <th>Task</th>
          <th>Created</th>
          <th>Due on</th>
          <th>Owner</th>
          <th>Assigned</th>
          <th>Mark</th>
        </tr>

        {% for task in tasks %}
          <tr id="{{ task.id }}">
            <td>
                <a href="{% url 'todo:task_detail' task.id %}">{{ task.title|truncatewords:10 }}</a>
            </td>
            <td>
                {{ task.created_date|date:"m/d/Y" }}
            </td>
            <td>
              <span {% if task.overdue_status %}class="overdue"{% endif %}>
                {{ task.due_date|date:"m/d/Y" }}
              </span>
            </td>
            <td>
              {{ task.created_by }}
            </td>
            <td>
              {% if task.assigned_to %}{{ task.assigned_to }}{% else %}Anyone{% endif %}
            </td>
            <td>
              <form method="post" action="{% url "todo:task_toggle_done" task.id %}" role="form">
                {% csrf_token %}
                <button class="btn btn-info btn-sm" type="submit" name="toggle_done">
                  {% if view_completed %}
                    Not Done
                  {% else %}
                    Done
                  {% endif %}
                </button>
              </form>
            </td>
          </tr>
        {% endfor %}
      </table>

      {% include 'todo/include/toggle_delete.html' %}

  {% else %}
    <h4>No tasks on this list yet  in "{{ task_list.name }}" (add one!)</h4>
    <h5><a href="{{ task_list.scope.project.get_absolute_url }}">{{ task_list.scope.project.job_num }} - {{ task_list.scope.project.job_name }} - {{ task_list.scope.project.jobsite }}</a></h5>
    {% include 'todo/include/toggle_delete.html' %}

  {% endif %}

{% endblock %}

{% block extra_js %}
  <script src="{% static 'todo/js/jquery.tablednd_0_5.js' %}" type="text/javascript"></script>

  <script type="text/javascript">
    function order_tasks(data) {
      // The JQuery plugin tableDnD provides a serialize() function which provides the re-ordered
      // data in a list. We pass that list as an object ("data") to a Django view
      // to save new priorities on each task in the list.
      $.post("{% url 'todo:reorder_tasks' %}", data, "json");
      return false;
    };

    $(document).ready(function() {
      // Initialise the task table for drag/drop re-ordering
      $("#tasktable").tableDnD();

      $('#tasktable').tableDnD({
        onDrop: function(table, row) {
          order_tasks($.tableDnD.serialize());
        }
      });

    });

    // When adding a task, change the text of the Add Task button
    function handleClick()
    {
        console.log(this.innerHTML);
        this.innerHTML = (this.innerHTML == 'Add Task' ? 'Cancel' : 'Add Task');
    }
    document.getElementById('AddTaskButton').onclick=handleClick;
  </script>
{% endblock extra_js %}

todo/templates/todo/list_lists.html
{% extends "todo/base.html" %}

{% block title %}<title>{{ list_title }} Todo Lists</title>{% endblock %}

{% block breadcrumb %} / <a href="{% url 'jobsite-list' %}">Job Site</a> / <a href="{% url 'project-list' %}">Project</a> / To Do List{% endblock %}

{% block content %}
  <h1>Todo Lists</h1>

  <p>{{ task_count }} tasks in {{ list_count }} list{{ list_count|pluralize }}</p>

  {% regroup lists by group as section_list %}
  <div class="row">
  {% for group in section_list %}
  <div class="col-lg-4">
    <div class="card mb-3">
    <h3>Group: {{ group.grouper }}</h3>
    <ul class="list-group mb-4">
      {% for task in group.list %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <a href="{{ task.scope.project.get_absolute_url }}">{{ task.scope.project.job_num }}</a> - <a href="{% url 'todo:list_detail' task.id task.slug %}">{{ task.name|truncatechars:35 }}</a> 
        <span class="badge badge-primary badge-pill">{{ task.task_set.count }}</span>
      </li>
      {% endfor %}
    </ul>
    </div>
  </div>
  {% endfor %}
  </div>

 

{% endblock %}

todo/templates/todo/search_results.html
{% extends "todo/base.html" %}

{% block title %}<title>Search results</title>{% endblock %}
{% block content_title %}<h2 class="page_title">Search</h2>{% endblock %}

{% block content %}
  {% if found_tasks %}
  <h2>{{found_tasks.count}} search results for term: "{{ query_string }}"</h2>
  <div class="post_list">
    {% for f in found_tasks %}
    <p>
      <strong>
        <a href="{% url 'todo:task_detail' f.id %}">{{ f.title }}</a>
      </strong>
      <br />
      <span class="minor">
        In list:
        <a href="{% url 'todo:list_detail' f.task_list.id f.task_list.slug %}">
          {{ f.task_list.name }}
        </a>
        <br /> Assigned to: {% if f.assigned_to %}{{ f.assigned_to }}{% else %}Anyone{% endif %}
        <br /> Complete: {{ f.completed|yesno:"Yes,No" }}
      </span>
    </p>
    {% endfor %}
  </div>
  {% else %}
    <h2> No results to show, sorry.</h2>
  {% endif %}
{% endblock %}