group/urls.py
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.conf.urls import url

app_name = 'group'
urlpatterns = [
    path('', views.group, name='group'),
    path('grouplist/', views.GroupListView.as_view(), name='group-list'),  
    re_path(r'^group-detail/(?P<id>\d+)$', views.GroupDeView, name='group-detail'),
    path('create-group/', views.GroupCreate.as_view(), name='create-group'),
    url(r'update-group/(?P<pk>[0-9]+)/$', views.GroupUpdate.as_view(), name='update-group'),
    url(r'group/(?P<pk>[0-9]+)/delete/$', views.GroupDelete.as_view(), name='delete-group'),
    path('albums', views.album, name='album'),
    path('albumlist/', views.AlbumListView.as_view(), name='album-list'),  
    re_path(r'^album-detail/(?P<id>\d+)$', views.AlbumDeView, name='album-detail'),
    path('create-album/', views.AlbumCreate.as_view(), name='create-album'),
    url(r'update-album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='update-album'),
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='delete-album')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import contactView, successView

app_name = 'home'
urlpatterns = [
    path('', views.index, name='home'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('contact/', contactView, name='contact'),
    path('success/', successView, name='success'),
    path('send-newsletter/', views.send_newsletter, name='send_newsletter'),
    path('unsubscribe/<str:email>/', views.unsubscribe, name='unsubscribe'),
    path('secret-lab/', views.easter_egg, name='easter_egg'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labmunkznetwork/urls.py
"""labmunkznetwork URL Configuration
"""
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.conf.urls import url

admin.site.site_header = "Labmunkz Network"
admin.site.index_title = "Database administration configuration."

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    #path('api/', include('api.urls')),
    path('group/', include('group.urls')),
    path('munkz/', include('munkz.urls')),
    path("music/", include("music.urls")),
    path("polls/", include("polls.urls")),
    path('shop/', include('shop.urls')),
   # path('asset/', include('asset.urls')),
    path('client/', include('client.urls')),
   # url(r'^filer/', include('filer.urls')),
   # path('helpdesk/', include('helpdesk.urls')),
    path('jobsite/', include('jobsite.urls')),
    path('project/', include('project.urls')),
    path('material/', include('material.urls')),
    path('posts/', include('posts.urls')),
    path('schedule/', include('schedule.urls', namespace='schedule')),
    path('timecard/', include('timecard.urls')),
    path('todo/', include('todo.urls', namespace="todo")),
   # path('wip/', include('wip.urls')),
]
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path, re_path
from django.conf.urls.static import static
from . import views
from django.conf.urls import url
from django.conf import settings
from .views import upload_mp3, analyze_mp3

app_name = 'music'
urlpatterns = [
    path('', views.MusicHomeView, name='music'),
    re_path(r'^music-detail/(?P<id>\d+)$', views.MusicDeView, name='music-detail'),
    path('contact/', views.contact, name='contact'),
    path('videos/', views.video_list, name='video_list'),
    path('upload/', upload_mp3, name='upload-mp3'),
    path('analyze/<int:mp3_id>/', analyze_mp3, name='analyze-mp3'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


schedule/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from django.views.generic.list import ListView
from . import views
#CalendarICalendar, 
from schedule.feeds import UpcomingEventsFeed
from schedule.models import Calendar
from schedule.periods import Day, Month, Week, Year
from schedule.views import (
    CalendarByPeriodsView, CalendarView, CancelOccurrenceView, CreateEventView, EventCreateView,
    CreateOccurrenceView, DeleteEventView, EditEventView, EditOccurrenceView,
    EventView, FullCalendarView, OccurrencePreview, OccurrenceView,
    api_move_or_resize_by_code, api_occurrences, api_select_create, EventTodayArchiveView, EventDayArchiveView,
)
app_name = 'schedule'
urlpatterns = [
    #re_path(r'^detail/schedule/(?P<pk>\d+)$', views.DayEventDetailView.as_view(), name='event-detail'),
    #path('create-event/', views.EventCreate.as_view(), name='create-event'), 
    url(r'create-event/(?P<proj>[0-9]+)$', views.EventCreateView, name='create-event'), 
    #url(r'schedule/update-event/(?P<pk>[0-9]+)/$', views.DayEventUpdate.as_view(), name='update-event'),
    #url(r'schedule/event/(?P<pk>[0-9]+)/delete/$', views.DayEventDelete.as_view(), name='delete-event'),
    path('today/', EventTodayArchiveView.as_view(), name='archive_today'),
    path('<int:year>/<str:month>/<int:day>/', EventDayArchiveView.as_view(), name='archive_day'),

    url(r'^$', ListView.as_view(model=Calendar), name='calendar_list'),

    url(r'^calendar/year/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_year.html'),
        name='year_calendar',
        kwargs={'period': Year}),

    url(r'^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_tri_month.html'),
        name='tri_month_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_compact_month.html'),
        name='compact_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_month.html'),
        name='month_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/week/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_week.html'),
        name='week_calendar',
        kwargs={'period': Week}),

    url(r'^calendar/daily/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_day.html'),
        name='day_calendar',
        kwargs={'period': Day}),

    url(r'^calendar/(?P<calendar_slug>[-\w]+)/$',
        CalendarView.as_view(),
        name='calendar_home',
        ),
    url(r'^fullcalendar/(?P<calendar_slug>[-\w]+)/$',
        FullCalendarView.as_view(),
        name='fullcalendar'),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        CreateEventView.as_view(),
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        EditEventView.as_view(),
        name='edit_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        EventView.as_view(),
        name='event'),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name='delete_event'),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        OccurrenceView.as_view(),
        name='occurrence'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        EditOccurrenceView.as_view(),
        name='edit_occurrence'),

    # urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        OccurrencePreview.as_view(),
        name='occurrence_by_date'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence_by_date'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CreateOccurrenceView.as_view(),
        name='edit_occurrence_by_date'),

    # feed urls
    url(r'^feed/calendar/upcoming/(?P<calendar_id>\d+)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    #url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),

    # api urls
    url(r'^api/occurrences', api_occurrences, name='api_occurrences'),
    url(r'^api/move_or_resize/$',
        api_move_or_resize_by_code,
        name='api_move_or_resize'),
    url(r'^api/select_create/$',
        api_select_create,
        name='api_select_create'),
    url(r'^$', ListView.as_view(queryset=Calendar.objects.all()), name='schedule'),
]

music/models.py
import datetime
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
from group.models import Album, Group
import os

def upload_to_artist_folder(instance, filename):
    # Normalize the artist name to be used as a folder name
    artist_name = instance.group_album.group.group_name.replace(' ', '_').lower()
    # Generate the folder path
    folder_name = f'media/{artist_name}/'
    # Return the full path to the file
    return os.path.join(folder_name, filename)

def upload_to_artist_folder2(instance, filename):
    # Normalize the artist name to be used as a folder name
    artist_name = instance.group_album.group.group_name.replace(' ', '_').lower()
    # Generate the folder path
    folder_name = f'music/{artist_name}/'
    # Return the full path to the file
    return os.path.join(folder_name, filename)

def upload_to_artist_folder3(instance, filename):
    # Normalize the artist name to be used as a folder name
    artist_name = instance.group.group_name.replace(' ', '_').lower()
    # Generate the folder path
    folder_name = f'video/{artist_name}/'
    # Return the full path to the file
    return os.path.join(folder_name, filename)

class AudioFile(models.Model):
    #  user adds_ 
    title = models.CharField(max_length=255, default='Unknown Title', help_text='Song Title')
    artist = models.CharField(max_length=255, default='Unknown Artist', help_text='Song Artist')
    album = models.CharField(max_length=255, default='Unknown Album', help_text='Song Album')
    G_STATUS = (
        ('q', 'Unknown Genre'),('a', 'Hip-Hop'),('b', 'Rock'),('c', 'Pop'),('d', 'Jazz'),('e', 'Classical'),('f', 'Electronic'),    
        ('g', 'Country'),('h', 'Reggae'),('i', 'Blues'),('j', 'R&B/Soul'),('k', 'Metal'),('l', 'Folk'),('m', 'Rock'),('n', 'Punk'),('o', 'Funk'),
        ('p', 'Disco'),('r', 'Gospel'),('s', 'Ska'),('t', 'Latin'),('u', 'Alternative'),('v', 'K-Pop'))
    genre = models.CharField(max_length=1, choices=G_STATUS, blank=True, default='a', help_text='Song Genre')
    year = models.CharField(max_length=4, default='2000', help_text='Song Year')    
    track_number = models.CharField(max_length=255, default='Unknown Track Number', help_text='Song Track Number')
    comment = models.CharField(max_length=255, default='No Comment', help_text='Song Comment')
    composer = models.CharField(max_length=255, default='Unknown Composer', help_text='Song Composer')
    lyrics = models.CharField(max_length=4320, default='No Lyrics', help_text='Song Lyrics')
    album_artist = models.CharField(max_length=255, default='Unknown Album Artist', help_text='Song Album Artist')
    disc_number = models.CharField(max_length=255, default='Unknown Disc Number', help_text='Song Disc Number')
    publisher = models.CharField(max_length=255, default='Unknown Publisher', help_text='Song Publisher')
    original_artist = models.CharField(max_length=255, default='Unknown Original Artist', help_text='Song Original Artist')
    encoded_by = models.CharField(max_length=255, default='Unknown Encoder', help_text='Song Encoder')
    contact_email = models.EmailField(max_length=254, blank=True, help_text='Contact@email.com')
    album_art = models.ImageField(upload_to=upload_to_artist_folder, null=True, blank=True, max_length=60, help_text='albumcover.jpg')
    audio_file = models.FileField(upload_to=upload_to_artist_folder2, null=True, blank=True, max_length=180, help_text='TrackName.mp3') 
    rms_list = models.CharField(max_length=1200000, default='Unknown RMS', help_text='Song RMS')
    rms_bass = models.CharField(max_length=1200000, default='Unknown Bass RMS', help_text='Song Bass')
    rms_mid = models.CharField(max_length=1200000, default='Unknown Mids RMS', help_text='Song Mids')
    rms_treble = models.CharField(max_length=1200000, default='Unknown Treb', help_text='Song Treb')  
    discript = models.CharField(max_length=1200, default='Unknown User Discription', help_text='Song User Discription')
    up_date = models.DateTimeField('date published', default='03/11/2002')
    #  fan adds_    
    heard = models.BigIntegerField(default=1)
    likes = models.BigIntegerField(default=1)
    nots = models.BigIntegerField(default=1)
    dls = models.BigIntegerField(default=1)
    group_album = models.ForeignKey(Album, on_delete=models.SET_NULL, blank=True, null=True, help_text='Album')
    munk = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, related_name="audiofile", related_query_name="audiofile", on_delete=models.SET_NULL)

    def __str__(self):
        return self.title
    
    def was_published_recently(self):
        return self.up_date >= timezone.now() - datetime.timedelta(days=1)
    
    @admin.display(
        boolean=True,
        ordering='up_date',
        description='Published recently?',)

    def get_absolute_url(self):
        
            """Returns the url to access a detail record for this install."""
            
            return reverse('audiofile', args=[str(self.pk)])

class Video(models.Model):
    VIDEO_TYPE_CHOICES = [
        ('youtube', 'YouTube'),
        ('uploaded', 'Uploaded'),
    ]

    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, help_text='Group')
    video_type = models.CharField(max_length=10, choices=VIDEO_TYPE_CHOICES)
    youtube_url = models.URLField(blank=True, null=True)  # For YouTube videos
    video_file = models.FileField(upload_to=upload_to_artist_folder3, blank=True, null=True, max_length=180, help_text='TrackName.mp4')  # For uploaded videosmodels.FileField(upload_to=upload_to_artist_folder2, null=True, blank=True, max_length=180, help_text='TrackName.mp3')
    published_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

music/forms.py
# music/forms.py

from django import forms
from .models import AudioFile

class MP3UploadForm(forms.ModelForm):
    class Meta:
        model = AudioFile
        fields = ['title', 'artist', 'album', 'group_album', 'track_number', 'munk', 'up_date', 'genre', 'year', 'audio_file', ]

    audio_file = forms.FileField(label="Upload MP3", required=True)

class AudioFileForm(forms.ModelForm):
    class Meta:
        model = AudioFile
        fields = ['title', 'artist', 'album', 'year', 'track_number', 
                  'comment', 'composer', 'lyrics', 'album_artist', 'disc_number', 'publisher', 
                  'original_artist', 'encoded_by', 'album_art', 'discript', 'rms_list', 
                  'rms_bass', 'rms_mid', 'rms_treble', 'heard', 'likes', 'nots', 'dls']

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)




music/templates/base_music.html
{% extends "home/base.html" %}

{% block title %}<title>Artist</title>{% endblock %}
{% block breadcrumb %} / <a href="{% url 'artist' %}">artist Section</a> / Choose by first letter. ({{ num_artists }}) artists {% endblock %}

{% block content %}
<div style="display: flow-root;">
  <a href="{% url 'artist-results' artist_list_a %}"><div class="alphabuttons">A </div></a> 
  <a href="{% url 'artist-results' artist_list_b %}"><div class="alphabuttons">B </div></a> 
  <a href="{% url 'artist-results' artist_list_c %}"><div class="alphabuttons">C </div></a>
  <a href="{% url 'artist-results' artist_list_d %}"><div class="alphabuttons">D </div></a> 
  <a href="{% url 'artist-results' artist_list_e %}"><div class="alphabuttons">E </div></a></div> 
<div style="display: flow-root;"> 
  <a href="{% url 'artist-results' artist_list_f %}"><div class="alphabuttons">F </div></a> 
  <a href="{% url 'artist-results' artist_list_g %}"><div class="alphabuttons">G </div></a>
  <a href="{% url 'artist-results' artist_list_h %}"><div class="alphabuttons">H </div></a> 
  <a href="{% url 'artist-results' artist_list_i %}"><div class="alphabuttons">I </div></a> 
  <a href="{% url 'artist-results' artist_list_j %}"><div class="alphabuttons">J </div></a></div> 
<div style="display: flow-root;"> 
  <a href="{% url 'artist-results' artist_list_k %}"><div class="alphabuttons">K </div></a> 
  <a href="{% url 'artist-results' artist_list_l %}"><div class="alphabuttons">L </div></a>
  <a href="{% url 'artist-results' artist_list_m %}"><div class="alphabuttons">M </div></a> 
  <a href="{% url 'artist-results' artist_list_n %}"><div class="alphabuttons">N </div></a> 
  <a href="{% url 'artist-results' artist_list_o %}"><div class="alphabuttons">O </div></a> </div> 
<div style="display: flow-root;"> 
  <a href="{% url 'artist-results' artist_list_p %}"><div class="alphabuttons">P </div></a>
  <a href="{% url 'artist-results' artist_list_q %}"><div class="alphabuttons">Q </div></a> 
  <a href="{% url 'artist-results' artist_list_r %}"><div class="alphabuttons">R </div></a> 
  <a href="{% url 'artist-results' artist_list_s %}"><div class="alphabuttons">S </div></a> 
  <a href="{% url 'artist-results' artist_list_t %}"><div class="alphabuttons">T </div></a> </div> 
<div style="display: flow-root;">
  <a href="{% url 'artist-results' artist_list_u %}"><div class="alphabuttons">U </div></a> 
  <a href="{% url 'artist-results' artist_list_v %}"><div class="alphabuttons">V </div></a> 
  <a href="{% url 'artist-results' artist_list_w %}"><div class="alphabuttons">W </div></a> 
  <a href="{% url 'artist-results' artist_list_x %}"><div class="alphabuttons">X </div></a>
  <a href="{% url 'artist-results' artist_list_y %}"><div class="alphabuttons">Y </div></a> </div> 
<div style="display: flow-root;">
  <a href="{% url 'artist-results' artist_list_z %}"><div class="alphabuttons">Z </div></a> 
  <a href="list/#"><div class="alphabuttons">#/all</div></a>   
  <div style="float: left; width: 64px; padding: 12px; margin: 6px;"></div>   
  <div style="float: left; width: 64px; padding: 12px; margin: 6px;"></div> 
    {% if request.user.staff %}
      <a href="{% url 'create-artist' %}"><div class="alphabuttons">new</div></a>
    {% else %}
      <div style="float: left; width: 64px; padding: 12px; margin: 6px;"></div>
    {% endif %} 
</div>
{% endblock %}

music/templates/music_home.html
{% extends "home/base.html" %}
{% load static %}
{% block title %}<title id="songTitle2">Music Home - Press Play</title>{% endblock %}
{% block breadcrumb %} / <a href="{% url 'music:music' %}">Music</a> / List
  {% if request.user.is_staff %} /<a href="{% url 'music:create-music' %}"> add a new music</a>{% else %}{% endif %}
{% endblock %}
{% block scripter %}
    <script src="{% static 'home/js/musicplayer.js' %}"></script>      
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock %}

{% block content %}
<div class="container-music">
    <div class="business-card-music">
        <section id="music-player">
            <div class="music-player">
              <audio id="audioPlayer" controls hidden>
                  <source id="audioSource" src="{{ music_list.0.audio_file.url}}" type="audio/mpeg">
                  Your browser does not support the audio element.
              </audio>
            <div class="card-header">
              <div class="search-container">
                <input type="text" id="searchInput" placeholder="Search playlist..." />
              </div>
              <div class="undersearch">
                <div id="songAlbum">{{ music_list.0.group_album }}</div>
                <div id="songArtist">{{ music_list.0.group_album.group }}</div>
              </div>
              {% if music_list.0.album_art %}
                <div class="image-container">
                  <img src="{% static '/home/css/racordspinclear.png' %}" class="image-front">
                  <img id="songArt" src="{{ music_list.0.album_art.url }}" alt="Back Image" class="image-back">
                </div>
              {% else %}
                <div class="image-container">
                  <img src="{% static '/home/css/racordspinclear.png' %}" class="image-front">
                  <img id="songArt" src="music_list.0.group_album.cover_art.url" alt="Back Image" class="image-back">
                </div>
              {% endif %}
              <div class="radiocontainer">
                <div class="back-layer"></div>
                <div class="middle-layer">
                    <div class="controls">
                      <div class="radio-left"><button id="prevBtn"><i style="margin:  0 0 7px 40px;" class="fas fa-backward"></i></button></div>
                      <div class="radio-play"><button id="playPauseBtn" style="font-size: x-large; margin: 0 3px 7px 0;"><i class="fas fa-play"></i></button></div>
                      <div class="radio-right"><button id="nextBtn"><i style="margin: 0 44px 7px 0;" class="fas fa-forward"></i></button></div>
                    </div>
                </div>
                <div class="top-layer">
                  <h1>
                    <div id="songTitle" style="text-shadow: 0 0 black;">
                    {{ music_list.0.title|slice:":29" }}{% if music_list.0.title|length > 29 %}...{% endif %}
                    </div>
                  </h1>
                  <div class="custom-audio-player">
                      <span id="currentTime">0:00</span> / <span id="duration">0:00</span>
                      <input type="range"  class="custom-range" id="seekBar" value="0" max="100">
                  </div>
                  <div class="custom-audio-player">
                      Volume<input type="range"  class="custom-range" id="volumeBar" min="0" max="1" step="0.1" value="1">
                  </div>
                </div>
              </div>
            </div>
            <div class="playlist">    
                {% if music_list %}
                    <ul id="playlist">
                        {% for song in music_list %}
                          {% if song.audio_file %}
                          <div class="track">
                              <div class="track-info">
                                  <div class="details" style="width:100%;">
                                      <p class="track-title">
                                        <li data-src="{{ song.audio_file.url }}" songTitle="{{ song.title }}" songAlbum="{{ song.group_album }}" songArtist="{{ song.group_album.group }}" songArt="{{ song.group_album.cover_art.url }}">
                                        {{ song.track_number }} - {{ song.title }} ▶
                                        </li>
                                      </p>                             
                                      <p style="font-size:small;" class="track-artist">{{ song.group_album }} - {{ song.group_album.group }}</p>
                                  </div>
                                  <div class="buttons">
                                      <a style="color:brown" href="{% url 'music:music-detail' song.pk %}">Song Details</a>
                                  </div>
                              </div>
                          </div>
                          {% else %}
                          <li>{{ song.title }} &raquo; {{ song.group_album }} - {{ song.group_album.group }} - {{ song.track_number  }} Sorry, no audio file!</li>
                          {% endif %} 
                        {% endfor %}
                    </ul>
                {% else %}
                There are no SONGS to list sorry!
                {% endif %} 
            </div>  
            <div class="music-player-bott">
            </div>
        </div>
    </section>
    </div>
    <div class="business-card-music">
      <table width="100%" cellspacing="0" style="border-radius: 8%;">
        <tbody>
        {% if album_list %}
          {% for album in album_list %}
              <tr>
                {% if album.cover_art %}
                  <td style="width: 150px;">
                    <a class="album-art" style="color:black;font-weight:bold;" href="#" onclick="searchAlbum('{{ album.title }}')">
                        <img src="{{ album.cover_art.url }}" alt="Album Art">
                    </a> 
                  </td>
                {% else %}
                  <td style="width: 150px;">
                    <a class="album-art" style="color:black;font-weight:bold;" href="#" onclick="searchAlbum('{{ album.title }}')">
                        <img src="{% static '/home/images/LMNlogo.jpg' %}" alt="Album Art">
                    </a> 
                  </td>
                {% endif %}
                <td>
                  <div class="album-card">
                    <a style="color:black;font-weight:bold;" href="{% url 'group:album-detail' album.id %}">
                      <h2>{{ album.title }}</h2>{{ album.group.group_name }}
                    </a> 
                  </div>
                </td>
              </tr>
          {% endfor %}
          {% else %}
          <tr>
              <td>There are no  </td>
              <td>album </td>
              <td>to list sorry!  </td>
          </tr>
        {% endif %} 
        </tbody>
      </table>
    </div>
</div>
{% endblock %} 

   

music/templates/music_list.html
{% extends "home/base.html" %}
{% load static %}
{% block title %}<title>Music List</title>{% endblock %}
{% block breadcrumb %} / <a href="{% url 'music:music' %}">Music</a> / List
  {% if request.user.staff %} /<a href="{% url 'create-music' %}"> add a new music</a>{% else %}{% endif %}
{% endblock %}

{% block content %}
<div class="table-responsive">
  <table class="table table-bordered" id="dataTable" width="90%" cellspacing="0">
    <thead>
      <tr>
        <th style="font-weight: inherit;">Music <i class="fa fa-id-card-o"></i> </th>
        <th style="font-weight: inherit;">Artist<i class="fa fa-fw fa-user"></i> </th>
        <th style="font-weight: inherit;">Album<i class="fa fa-phone"></i> </th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th style="min-width:64px; font-weight: inherit;">music <i class="fa fa-id-card-o"></i> </th>
        <th style="font-weight: inherit;"><i class="fa fa-fw fa-user"></i> </th>
        <th style="min-width:120px; font-weight: inherit;"><i class="fa fa-phone"></i> </th>
      </tr>
    </tfoot>
    <tbody>
          {% if music_list %}
          {% for music in music_list %}
              <tr>
                <td><a style="color:black;font-weight:bold;" href="{% url 'music:music-detail' music.id %}">{{ music.title }}</a> </td>
                <td><a style="color:black;font-weight:bold;" href="{% url 'group:group-detail' music.group_album.group.id %}">{{ music.group_album.group }}</a> </td>
                <td><a style="color:black;font-weight:bold;" href="{% url 'group:album-detail' music.group_album.id %}">{{ music.group_album }}</a> </td>
              </tr>
          {% endfor %}
          {% else %}
          <tr>
              <td>There are no  </td>
              <td>musics </td>
              <td>to list sorry!</td>
          </tr>
    <p>There are no nopes in this planet.</p>
  {% endif %} 
    </tbody>
  </table>
</div>
{% endblock %} 

{% block scripter %} 
{% endblock %}
   